// Copyright The Orca Authors
// SPDX-License-Identifier: Apache-2.0

/**
 * Fails when a tracked source file lacks the project's license header.
 *
 *   pnpm check:headers          # check; exit 1 and list offenders
 *   pnpm check:headers --fix    # add the header where it is missing
 *
 * Every source file carries two lines in its own comment syntax, in the
 * OpenTelemetry style and with no year:
 *
 *   Copyright The Orca Authors
 *   SPDX-License-Identifier: Apache-2.0
 *
 * A file is skipped when it can't hold a comment (JSON), when a tool owns it,
 * or when it is prose or data rather than source. Recipe fixtures are skipped
 * too: they are the agent's input, read verbatim. The skip list is explicit on
 * purpose: a new file type is checked until someone decides otherwise here.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const COPYRIGHT_LINE = 'Copyright The Orca Authors';
export const LICENSE_LINE = 'SPDX-License-Identifier: Apache-2.0';

type Prefix = '//' | '#';

/** How far into a file the header may sit (a shebang or modeline comes first). */
const HEADER_WINDOW_LINES = 10;

const SLASH_EXTENSIONS = new Set(['.ts', '.mts', '.cts', '.js', '.mjs', '.cjs']);
const HASH_EXTENSIONS = new Set(['.sh', '.bash', '.py', '.yaml', '.yml', '.toml']);

/** Paths that are never checked, each with the reason it is exempt. */
export const SKIPPED_PATHS: ReadonlyArray<readonly [RegExp, string]> = [
  [/^pnpm-lock\.yaml$/, 'generated by pnpm'],
  [/^\.github\/ISSUE_TEMPLATE\//, 'GitHub parses these forms itself'],
  [/^recipes\/[^/]+\/fixtures\//, 'recipe fixtures are agent input, read verbatim'],
];

export function isSkipped(path: string): boolean {
  return SKIPPED_PATHS.some(([pattern]) => pattern.test(path));
}

/** Returns the line-comment prefix for a path, or null when the path is not checked. */
export function commentPrefixFor(path: string): Prefix | null {
  if (isSkipped(path)) return null;
  const name = basename(path);
  const dot = name.lastIndexOf('.');
  if (dot <= 0) return null;
  const extension = name.slice(dot);
  if (SLASH_EXTENSIONS.has(extension)) return '//';
  if (HASH_EXTENSIONS.has(extension)) return '#';
  return null;
}

/**
 * Returns the comment prefix for an extension-less script, judged by its
 * shebang, or null when the file is not a script this gate checks.
 */
export function shebangPrefixFor(text: string): Prefix | null {
  const first = text.split('\n', 1)[0] ?? '';
  if (!first.startsWith('#!')) return null;
  if (/\b(node|deno|bun|tsx)\b/.test(first)) return '//';
  if (/\b(sh|bash|zsh|dash|python3?)\b/.test(first)) return '#';
  return null;
}

/** True when both header lines appear near the top of the text. */
export function hasHeader(text: string): boolean {
  const head = text.split('\n', HEADER_WINDOW_LINES).join('\n');
  return head.includes(COPYRIGHT_LINE) && head.includes(LICENSE_LINE);
}

/**
 * Lines that must stay above the header: a shebang, and a yaml-language-server
 * modeline, which editors look for on the first line.
 */
function isPinnedFirstLine(line: string, index: number): boolean {
  if (index !== 0) return false;
  return line.startsWith('#!') || /^#\s*yaml-language-server:/.test(line);
}

/** Returns the text with the header inserted after any pinned first line. */
export function addHeader(text: string, prefix: Prefix): string {
  const lines = text.split('\n');
  let insertAt = 0;
  while (insertAt < lines.length && isPinnedFirstLine(lines[insertAt] ?? '', insertAt)) {
    insertAt += 1;
  }
  const header = [`${prefix} ${COPYRIGHT_LINE}`, `${prefix} ${LICENSE_LINE}`];
  const next = lines[insertAt];
  // Keep one blank line between the header and whatever follows it.
  if (next !== undefined && next.trim() !== '') header.push('');
  lines.splice(insertAt, 0, ...header);
  return lines.join('\n');
}

function trackedFiles(root: string): string[] {
  const out = execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], {
    cwd: root,
    encoding: 'utf8',
  });
  return out.split('\0').filter(Boolean);
}

function main(): void {
  const root = fileURLToPath(new URL('..', import.meta.url));
  const fix = process.argv.includes('--fix');
  const missing: string[] = [];

  for (const path of trackedFiles(root)) {
    if (isSkipped(path)) continue;
    let prefix = commentPrefixFor(path);
    const extensionless = !basename(path).includes('.');
    if (prefix === null && !extensionless) continue;

    let text: string;
    try {
      text = readFileSync(join(root, path), 'utf8');
    } catch {
      continue; // deleted in the working tree but still in the index
    }

    if (prefix === null) {
      prefix = shebangPrefixFor(text);
      if (prefix === null) continue;
    }
    if (hasHeader(text)) continue;

    // Writing to the existing path keeps its mode, so executables stay executable.
    if (fix) writeFileSync(join(root, path), addHeader(text, prefix));
    else missing.push(path);
  }

  if (missing.length > 0) {
    console.error(`${missing.length} file(s) lack the license header:`);
    for (const path of missing) console.error(`  ${path}`);
    console.error(`\nThe header is two lines, "${COPYRIGHT_LINE}" and "${LICENSE_LINE}",`);
    console.error("in the file's comment syntax. Add it with:");
    console.error('  pnpm check:headers --fix');
    process.exit(1);
  }
  console.log('check-headers: ok');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
